version: "3.8"

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
    - ./front-end/src:/app/src
    - ./front-end/public:/app/public
    - ./front-end/package.json:/app/package.json
    - ./front-end/package-lock.json:/app/package-lock.json
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./back-end:/app
    env_file:
      - .env
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres

  postgres:
      image: postgres:13
      volumes:
        - postgres-data:/var/lib/postgresql/data
      env_file:
        - .env
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - "5432:5432"

volumes:
  postgres-data:



