version: "3.8"

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
    - ./front-end/src:/app/src
    - ./front-end/public:/app/public
    - ./front-end/package.json:/app/package.json
    - ./front-end/package-lock.json:/app/package-lock.json
    environment:
      - NODE_ENV=development
      - REACT_APP_OPENAI_API_KEY=${REACT_APP_OPENAI_API_KEY}
    env_file:
      - .env
    command: ["npm", "run", "dev"]
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./back-end:/app
    env_file:
      - .env
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      







