version: "3.8"

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
    - ./front-end/src:/app/src
    - ./front-end/public:/app/public
    - ./front-end/package.json:/app/package.json
    - ./front-end/package-lock.json:/app/package-lock.json
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
